myhomework25/accounts/urls.py
from django.urls import path
from accounts import views

app_name="accounts"

urlpatterns=[
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
    path('profile/',views.profile,name='profile'),
    path('logout/',views.logout,name='logout'),
]

myhomework25/ani/urls.py
from django.urls import path

from ani import views

app_name="ani"

urlpatterns=[
    path("",views.ani_list,name="ani_list"),
    path("<int:pk>/",views.ani_detail,name="ani_detail"),
    path("<int:ani_pk>/comments/new/",views.comment_new,name="comment_new"),
    path("<int:ani_pk>/comments/<int:pk>/edit/",views.comment_edit,name="comment_edit"),
    path('new/', views.ani_new, name='ani_new'),
    path('<int:pk>/edit/', views.ani_edit, name='ani_edit'),
    path('<int:pk>/delete/', views.ani_delete, name='ani_delete'),
]

myhomework25/myhomework25/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='root.html'),name="root"),
    path('ani/',include('ani.urls')),
    path('acoounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__/",include(debug_toolbar.urls)),
    ]

myhomework25/accounts/models.py
from django.db import models

# Create your models here.

myhomework25/ani/models.py
from django.db import models
from django.urls import reverse


class TimestampedModel(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

class Category(TimestampedModel):
    name=models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering=["name"]
        verbose_name="카테고리"
        verbose_name_plural="카테고리들"

class Ani(TimestampedModel):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=30,db_index=True)
    photo=models.ImageField(upload_to="ani/ani/%Y/%m/%d",blank=True)
    description=models.TextField(blank=True)
    tag_set=models.ManyToManyField('Tag',blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering=["name"]
        verbose_name="캐릭터"
        verbose_name_plural="캐릭터 이름들"

    def get_absolute_url(self):
        return reverse("ani:ani_detail",args=[self.pk])

class Comment(TimestampedModel):
    ani=models.ForeignKey(Ani,on_delete=models.CASCADE)
    user=models.CharField(max_length=30,db_index=True)
    message=models.TextField()

    def __str__(self):
        return self.message

    class Meta:
        ordering=["-id"]
        verbose_name="댓글"
        verbose_name_plural="댓글 목록"

class Tag(TimestampedModel):
    name=models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering=["name"]
        verbose_name="태그"
        verbose_name_plural="태그 목록"

myhomework25/ani/forms.py
from django import forms
from ani.models import Comment, Tag, Ani


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields = ["message"]

class AniForm(forms.ModelForm):
    tags=forms.CharField(required=False)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        if self.instance.pk:
            tag_qs=self.instance.tag_set.all()
            initial=",".join([tag.name for tag in tag_qs])
            self.fields["tags"].initial=initial

    def _save_m2m(self):
        super()._save_m2m()

        tag_list=[]
        tags=self.cleaned_data.get("tags","")

        for word in tags.split(","):
            tag_name=word.strip()
            tag,__=Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)

        self.instance.tag_set.clear()
        self.instance.tag_set.add(*tag_list)

    class Meta:
        model=Ani
        fields=[
            "category",
            "name",
            "photo",
            "description",
        ]

myhomework25/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

signup=CreateView.as_view(
    form_class=UserCreationForm,
    success_url=reverse_lazy("accounts:login"),
    template_name="accounts/signup_form.html",
)

login=LoginView.as_view(
    template_name="accounts/login_form.html",
)

profile=login_required(TemplateView.as_view(
    template_name="accounts/profile.html",
))

logout=LogoutView.as_view(
    next_page="root",
)

myhomework25/ani/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from ani.forms import CommentForm, AniForm
from ani.mixins import CommentUserCheckMixin
from ani.models import Ani, Category, Comment


class AniListView(ListView):
    model=Ani
    paginate_by=5

    def get_queryset(self):
        qs=super().get_queryset()

        query=self.request.GET.get("query","")
        if query:
            qs=qs.filter(name__icontains=query)

        return qs

    def get_context_data(self,**kwargs):
        context_date=super().get_context_data(**kwargs)
        context_date["category_list"]=Category.objects.all()
        return context_date

ani_list=AniListView.as_view()

ani_detail=DetailView.as_view(
    model=Ani,
)

class CommentCreateView(LoginRequiredMixin,CreateView):
    model=Comment
    form_class=CommentForm

    def form_valid(self, form)->HttpResponse:
        ani_pk=self.kwargs["ani_pk"]
        ani=get_object_or_404(Ani,pk=ani_pk)

        comment=form.save(commit=False)
        comment.ani=ani
        comment.user=self.request.user
        comment.save()

        return redirect(ani)

comment_new=CommentCreateView.as_view()



class CommentUdateView(LoginRequiredMixin, CommentUserCheckMixin, UpdateView): # 다중 상속
    model=Comment
    form_class=CommentForm
    # success_url = reverse_lazy("ani:ani_list")
    #
    # def test_func(self):
    #     commnet=self.get_object()
    #     return self.request.user==comment.user

    def get_success_url(self)->str:
        comment=self.object
        return resolve_url(comment.ani)

comment_edit=CommentUdateView.as_view()

comment_delete=DeleteView.as_view(
    model=Ani,
    success_url=reverse_lazy("ani:ani_list")
)

class AniCreateView(CreateView):
    model = Ani
    form_class=AniForm

    def get_success_url(self):
        ani_pk=self.object.pk
        return reverse("ani:ani_detail",args=[ani_pk])

ani_new=AniCreateView.as_view()


class AniUpdateView(UpdateView):
    model=Ani
    form_class=AniForm
ani_edit=AniUpdateView.as_view()

ani_delete=DeleteView.as_view(
    model=Ani,
    success_url=reverse_lazy("ani:ani_list"),
)

myhomework25/accounts/templates/accounts/login_form.html
{% extends "accounts/layout.html" %}
{% block content %}
    <h2>로그인</h2>
    {% include "_form.html" with submit_label="로그인"%}
{% endblock %}

myhomework25/accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}
{% block content %}
    <h2>{{ user }}의 프로필</h2>
{% endblock %}

myhomework25/accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}
{% block content %}
    <h2>회원가입</h2>
    {% include "_form.html" with submit_label="회원가입" %}
{% endblock %}

myhomework25/myhomework25/templates/_form.html
{% load bootstrap5 %}
<form action="" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary"
    {% if submit_label %} value="{{ submit_label }}"/>
    {% endif %}
</form>

myhomework25/myhomework25/templates/layout.html
{% load bootstrap5 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block page_title %}Kirby{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <h1>LOVE KIRBY</h1>
    <ul>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'accounts:login' %}">로그인</a></li>
            <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
        {% else %}
            <li><a href="{% url 'accounts:profile' %}">프로필</a></li>
            <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
        {% endif %}
    </ul>
    {% block content %}
    {% endblock %}
    <hr />
    &copy;권커비 컴퍼니
</body>
</html>

myhomework25/myhomework25/templates/root.html
{% extends "layout.html" %}
{% block content %}
    <p class="alert alert-info">
    welcome to kirby world!
    </p>
    <ul>
        <li><a href="{% url 'ani:ani_list' %}">캐릭터 리스트</a></li>
    </ul>
{% endblock %}