mydjango19/diary/urls.py
from django.urls import path

from diary import views

app_name="diary"

urlpatterns=[
    path("",views.post_list, name="post_list"),
    path("<int:pk>/",views.post_detail,name="post_detail"),# 주소 매칭
    path("new/",views.post_new,name="post_new"),
    path("<int:pk>/edit/", views.post_edit,name="post_edit"),
    path("tags/<str:tag_name>/",views.tag_detail,name="tag_detail"),
    path("<int:post_pk>/comments/new/",views.comment_new,name="comment_new"),
    path("<int:post_pk>/comments/<int:pk>/edit/",views.comment_edit,name="comment_edit"),
]

mydjango19/mydjango17/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

# TODO: 편의상 여기에 root를 구현하지만,
# 차후 RedirectView CBV를 써서 이 구현을 제거할 예정
# 최상위 페이지로 가면 바로 post_list로 이동하도록 설정
def root(request):
    return redirect("diary:post_list")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/',include('diary.urls')),
    path('',root,name="root"),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

# 디버그 툴바의 urls
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__/",include(debug_toolbar.urls)),
    ]

mydjango19/diary/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class TimestampedModel(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True # 추상 클래스로서, DB 테이블이 생기지 않는다다

#db_index는 db에 인덱스를 생성시켜 조건을 넣으면 검색이 가능하게 하는 부분
class Post(TimestampedModel):
    author_name=models.CharField(max_length=20)
    title=models.CharField(max_length=200, db_index=True,validators=[
        MinLengthValidator(3),
        # MaxLengthValiadtor(),는 따로 할 필요가 없다 내부에 max_length=200을 설정해줬기 때문
    ],)
    content=models.TextField()
    photo=models.ImageField(upload_to="diary/post/%Y/%m/%d")
    # 그냥 Tag를 적으면 Tag가 아래에 있기에 받지 못한다
    # 문자열로 넣어주면 현재 앱에서 Tag를 찾아 받아준다
    # tag_set이 아닌 tag라고 하면 단수형이기에 의미가 좋지는 않다
    tag_set=models.ManyToManyField('Tag',blank=True)
    ip = models.GenericIPAddressField()

    def __str__(self)->str:
        return f"[{self.pk}] {self.title}"

    class Meta:
        # 단수
        verbose_name="포스팅"
        # 복수
        verbose_name_plural="포스팅 목록"

class Comment(TimestampedModel):
    # 외래키: 정수값
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    # post_id
    author_name=models.CharField(max_length=20)
    message=models.TextField()

    class Meta:
        verbose_name="댓글"
        verbose_name_plural="댓글 목록"

class Tag(TimestampedModel):
    name=models.CharField(max_length=200, db_index=True)

    def __str__(self)->str:
        return self.name

    class Meta:
        verbose_name="태그"
        verbose_name_plural="태그 목록"

#class에 TimestampedModel를 넣음으로 상속을 하는 것

mydjango19/diary/forms.py
from django import forms
from django.core.validators import RegexValidator

# class PostForm(forms.Form):
#     title = forms.CharField()
#     content = forms.CharField()
#     phone = forms.CharField(
#         validators=[
#             RegexValidator(r"^\d{3}-?\d{4}-?\d{4}$", message="휴대폰 번호를 입력해주세요."),
#         ]
#     )
#
from diary.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        # fields="__all__"
        # 유저로부터 입력받을 필드 이름을 나열
        fields = [
            "author_name",
            "title",
            "content",
            "photo",
            "tag_set",
        ]

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=["author_name","message"]

mydjango19/diary/views.py
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404

from diary.forms import PostForm, CommentForm
from diary.models import Post, Comment

from django.contrib import messages

def tag_detail(request: HttpRequest, tag_name:str)->HttpResponse:
    qs=Post.objects.all()
    qs=qs.filter(tag_set__name=tag_name)
    return render(request,"diary/tag_detail.html",{
        "tag_name": tag_name,
        "post_list":qs,
    })

def post_list(request: HttpRequest)->HttpResponse:
    qs=Post.objects.all() # 전체 포스팅 목록을 얻어올 준!비!
    query=request.GET.get("query","")
    if query: # 검색어가 있다면
        qs=qs.filter(title__icontains=query)

    return render(request,"diary/post_list.html",{
        "post_list":qs,
    })

def post_detail(request:HttpRequest, pk:int) -> HttpResponse:
    post=get_object_or_404(Post, pk=pk)
    # try:
    #     post=Post.objects.get(pk=pk)
    # except Post.DoesNotExist:
    #     raise Http404 # 예외는 return이 아니라 raise로 해야함

    comment_list=post.comment_set.all()
    tag_list=post.tag_set.all()
    return render(request,"diary/post_detail.html",{
        "post":post,
        "comment_list":comment_list,
        "tag_list":tag_list,
    })

def post_new(request: HttpRequest) -> HttpResponse:
    # if request.method == "GET" # 빈서식
    #     form=PostForm()
    # else: # 입력 값을 전달받아 유효성 검사->저장
    #     form = PostForm(request.POST,request.FILES)

    # form.save(!!!2 전체 작성 후 commit=False)
    # !!!2 post.ip=request.META["REMOTE_ADDR"]
    if request.method=="POST":
        form=PostForm(request.POST,request.FILES)
        if form.is_valid(): # 관심있어하는 모든 것의 유효성을 검사하는데 하나라도 실패시 실패
            # form.cleaned.data
            post=form.save(commit=False)
            post.ip=request.META["REMOTE_ADDR"]
            post.save()
            messages.success(request,"성공적으로 저장했습니다.")
            return redirect("diary:post_list")
    else:
        form=PostForm()

    return render(request, "diary/post_form.html", {
        "form": form,
    })

def post_edit(request: HttpRequest, pk:int) -> HttpResponse:
    # 아래 코드는 ModelForm에 한해서 동작하는 코드
    #post=Post.objects.get(pk=pk)
    post=get_object_or_404(Post,pk=pk)
    if request.method=="POST":
        form=PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            form.save()
            messages.success(request,"성공적으로 수정했습니다")
            return redirect("diary:post_list")
    else:
        form=PostForm(instance=post)

    return render(request, "diary/post_form.html", {
        "form": form,
    })

# /diary/100/comments/new/
def comment_new(request, post_pk:int)->HttpResponse:
    post=Post.objects.get(pk=post_pk)
    if request.method == "POST":
        form=CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # form.cleaned_data # 유효성 검사에 통과한 값을 dict
            comment=form.save(commit=False)
            # comment.post_id=post_pk #FK를 직접 채우진 않는다
            comment.post=post
            comment.save()
            return redirect("diary:post_detail",post_pk)
    else:
        form=CommentForm()
    return render(request,"diary/comment_form.html",{
        "form":form,
    })
# /diary/100/comments/20/edit/
# pk는 수정할 인자=2번째 인자
def comment_edit(request, post_pk:int, pk:int)->HttpResponse:
    comment=get_object_or_404(Comment,pk=pk)
    form=CommentForm(instance=comment)
    return render(request,"diary/comment_form.html",{
        "form":form,
    })

mydjango19/diary/templates/diary/comment_form.html
{% extends "diary/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>Comment Form</h2>
    <!-- form.as_table+중괄감싸지 기본 호출 형태 -->

   <!-- 검색은 get 삭제 수정은 post -->
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} <!-- post일 때만 붙고 get은 안 붙음 -->
        <!-- 템플릿만의 함수 -->
        {% bootstrap_form form %}
        <input type="submit"
                value="저장하기"
                class="btn btn-primary"/>
    </form>
{% endblock %}

mydjango19/diary/templates/diary/layout.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>하웅이의 Diary</title>

    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <style>
        body{
            padding-bottom: 1em;
        }
    </style>
</head>
<div>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="{% url "root" %} "class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">하웅이의 블로그</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
    </header>
        {% if messages %}
            {% for message in messages  %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message.tags }}
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
<hr />
&copy; 하웅이 컴퍼니
</div>
</body>
</html>

mydjango19/diary/templates/diary/post_detail.html
{% extends "diary/layout.html" %}
{% block content %}
    <h2>{{ post.title }}</h2>
    <p>
        태그:
        {% for tag in tag_list %}
            <a href="{% url "diary:tag_detail" tag.name %}" class="badge bg-success">
                {{ tag.name }}
            </a>
        {% endfor %}

    </p>

    <img src="{{ post.photo.url }}" alt="{{ post.title }}"/>

    {{ post.content|linebreaks }} <!-- p태그 -->

    <h3>댓글</h3>
    <a href="{% url "diary:comment_new" post.pk %}">댓글쓰기</a>
    <ul>
        {% for comment in comment_list %}
            <li>
                {{ comment.message }}
                by {{ comment.author_name }}
                at
                <span title="{{ comment.created_at }}">
                {{ comment.created_at|timesince }}전
                </span>
                <a href="/diary/{{ post.pk }}/comments/{{ comment.pk }}/edit/">Edit</a>
{#                <a href="{% url "diary:comment_edit" post.pk comment.pk %}">Edit</a>#}
            </li>

        {% endfor %}
    </ul>
    <hr />

    <a href="{% url "diary:post_list" %}">목록으로</a>
    <a href="{% url "diary:post_edit" post.pk %}">수정하기</a>
{% endblock %}

mydjango19/diary/templates/diary/post_form.html
{% extends "diary/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>Post Form</h2>
    <form action="" method="post" enctype="multipart/form-data"> <!-- 주소를 깔끔하게 바꿔줬다 -->
        {% csrf_token %}
{#        <table>#}
{#        {{ form.as_table }}#}
{#        </table>#}
        {% bootstrap_form form %} <!-- 테이블로 설정했던 것 부트스트랩으로 바꿔서 디자인 -->
        <input type="submit" value="저장하기"/>
    </form>
{% endblock %}

mydjango19/diary/templates/diary/post_list.html
{% extends "diary/layout.html" %}

<!-- block안에 지정해주지 않는 것은 무시된다 -->
{% block content %}
    <form action="" method="get">
        <input type="text" name="query" value="{{ request.GET.query }}"placeholder="웹 검색어를 지정해주세요"/>
        <!-- value를 지정해서 검색해도 검색했던 단어가 사라지지 않게 함 -->
        <input type="submit" value="검색"/>
    </form>
    <div class="row" style="margin-top:1em;">
    <!-- views에서 지정해준 것을 in 뒤에 넣어줘야함  -->
        {% for post in post_list %}
            <div class="col-sm-6 offset-sm-3" style="margin-top:1em;">
                <div class="card">
                    <img src="{{ post.photo.url }}"
                         alt="{{ post.title }}"
                         class="card-img-top"/>
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        {{ post.content|truncatewords:20 }}
                <a href="{% url "diary:post_detail" post.pk %}" class="btn btn-sm btn-primary">바로가기</a>
            </div></div></div>
        {% endfor %}
    </div>
    <hr />
    <a href="{% url "diary:post_new" %}" class="btn btn-primary">
        포스팅 쓰기</a>
{% endblock %}

mydjango19/diary/templates/diary/tag_detail.html
{% extends "diary/layout.html" %}
{% block content %}
    <h2>{{ tag_name }}</h2>
    <div>
        {% for post in post_list %}
            <div>
                <a href="{% url "diary:post_detail" post.pk %}">
                {{ post.title }}
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}