myhomework21/myhomework21/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('volleyball/',include('volleyball.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__/",include(debug_toolbar.urls)),
    ]

myhomework21/volleyball/urls.py
from django.urls import path

from volleyball import views

app_name="volleyball"

urlpatterns=[
    path("",views.player_list,name="player_list"),
    path("<int:pk>/",views.player_deatil,name="player_detail"),
    path("new/",views.player_new,name="player_new"),
    path("<int:pk>/edit/",views.player_edit,name="player_edit"),
]

myhomework21/volleyball/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=100,unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["-name"]


class Player(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=30,db_index=True)
    photo=models.ImageField(upload_to="volleyball/player/%Y/%m/%d")
    position=models.CharField(max_length=30)
    description=models.TextField(blank=True)
    tag_set=models.ManyToManyField('Tag',blank=True)

    def __str__(self)->str:
        return self.name

    class Meta:
        ordering=["-name"]

class Tag(models.Model):
    name=models.CharField(max_length=100,unique=True)

    def __str__(self)->str:
        return self.name

    class Meta:
        ordering=["-name"]

myhomework21/volleyball/forms.py
from django import forms

from volleyball.models import Player, Tag


class PlayerForm(forms.ModelForm):
    tags=forms.CharField()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        if self.instance.pk:
            tag_qs=self.instance.tag_set.all()
            tags=",".join([tag.name for tag in tag_qs])
            self.fields["tags"].initial=tags

    def save(self):
        saved_post=super().save()

        tag_list=[]
        tags=self.cleaned_data.get("tags","")
        for word in tags.split(","):
            tag_name=word.strip()
            tag,__=Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)

        saved_post.tag_set.clear()
        saved_post.tag_set.add(*tag_list)

        return saved_post

    class Meta:
        model=Player
        fields=[
            "category",
            "name",
            "photo",
            "position",
            "description",
        ]

myhomework21/volleyball/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from volleyball.forms import PlayerForm
from volleyball.models import Player, Category


def player_list(request:HttpRequest)->HttpResponse:
    category_qs=Category.objects.all()
    qs=Player.objects.all()
    query=request.GET.get("query","")
    category_id:str = request.GET.get("category_id","")
    if category_id:
        qs=qs.filter(category__pk=category_id)
    if query:
        qs=qs.filter(name__icontains=query)
    return render(request,"volleyball/player_list.html",{
        "player_list":qs,
        "category_list":category_qs,
    })

def player_deatil(request:HttpRequest,pk:int)->HttpResponse:
    player=get_object_or_404(Player,pk=pk)
    return render(request,"volleyball/player_detail.html",{
        "player":player,
    })

def player_new(request:HttpRequest)->HttpResponse:
    if request.method=="POST":
        form=PlayerForm(request.POST,request.FILES)
        if form.is_valid():
            saved_post=form.save()
        return redirect("volleyball:player_detail",saved_post.pk)
    else: form=PlayerForm()
    return render(request,"volleyball/player_form.html",{
        "form":form,
    })

def player_edit(request:HttpRequest,pk:int)->HttpResponse:
    player=get_object_or_404(Player,pk=pk)
    if request.method=="POST":
        form=PlayerForm(request.POST,request.FILES,instance=player)
        if form.is_valid():
            saved_player=form.save()
        return redirect("volleyball:player_detail",saved_player.pk)
    else: form=PlayerForm(instance=player)
    return render(request,"volleyball/player_form.html",{
        "form":form,
    })

myhomework21/volleyball/templates/volleyball/layout.html
{% load bootstrap5 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>VolleyBall</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<div class="container">
    {% bootstrap_messages %}
    <h1>VolleyBall Player</h1>
    {% block content %}
    {% endblock %}
    <hr />
    &copy; 2021 권하은 컴퍼니
</div>
</body>
</html>

myhomework21/volleyball/templates/volleyball/player_detail.html
{% extends "volleyball/layout.html" %}
{% block content %}
    <h2>{{ player.name }}</h2>
    <p>
        {% for tag in player.tag_set.all %}
            <span class="badge bg-success">{{ tag.name }}</span>
        {% endfor %}
    </p>
    <img src="{{ player.photo.url }}" alt="{{ player.name }}" />
    <ul>
        <li>{{ player.name }}</li>
        <li>{{ player.position }}</li>
    </ul>
    {{ player.description|linebreaks }}
    <hr />
    <a href="{% url "volleyball:player_edit" player.pk %}" class="btn bg-primary">게시글 수정</a>
    <a href="{% url "volleyball:player_list" %}" class="btn bg-primary">목록으로</a>
{% endblock %}

myhomework21/volleyball/templates/volleyball/player_form.html
{% extends "volleyball/layout.html" %}

{% block content %}
    <h2>Form</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="저장하기"/>
    </form>
{% endblock %}

myhomework21/volleyball/templates/volleyball/player_list.html
{% extends "volleyball/layout.html" %}
{% block content %}
    <h2>Player List</h2>
    <div class="row">
    <div class="col-sm-8">
        <ul>
            {% for player in player_list %}
                <img src="{{ player.photo.url }}" alt="{{ player.name }}"/>
                <li>
                <a href="{% url "volleyball:player_detail" player.pk %}">{{ player.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-sm-4">
    <div calss=".d-grid mb-3">
        <a href="{% url "volleyball:player_new" %}" class="btn btn-primary">새 포스팅 쓰기</a>
        <form action="" method="get">
            <input type="text" name="query" placeholder="검색할 선수를 입력해주세요" value="{{ request.GET.query }}"/>
            <input type="submit" value="검색"/>
        </form>
    <ul>
        <li>
            <a href="?category_id=">카테고리 전체</a>
        </li>
        {% for category in category_list %}
            <li>
                <a href="?category_id={{ category.pk }}">{{ category.name }}</a>
            </li>
        {% endfor %}
    </ul>
    </div></div></div>



{% endblock %}